name: CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest
# this is a continuous integration script to run everything we've done so far, I think
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

# pipe symbol indicates a script
      - name: test with pytest
        run: | 
          python -m pytest --cov=catchment.models tests/test_models.py
          
