name: CI

on: push

jobs:

  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{matrix.os}}

# this is a continuous integration script to run everything we've done so far, I think
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

# pipe symbol indicates a script
      - name: test with pytest
        run: | 
          python -m pytest --cov=catchment.models tests/test_models.py
          
